version: "3.9"

services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: collectiv/backend:latest
    environment:
      - GITHUB_PACKAGES_TOKEN=${GITHUB_PACKAGES_TOKEN}
    ports:
      - "3001:3001"
    networks: 
      - webproxy
    env_file: ./apps/backend/.docker.env
  
    #restart: unless-stopped

  frontend:
    image: collectiv/frontend:latest
    environment:
      - GITHUB_PACKAGES_TOKEN=${GITHUB_PACKAGES_TOKEN}
    env_file: ./apps/frontend/.docker.env
    #restart: unless-stopped


networks:
  # external network
  webproxy:
    name: webproxy
    external: true
  

volumes:
  db-data:
